// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Board struct {
	Rows []string `json:"rows"`
}

type Game struct {
	ID    string `json:"id"`
	Board *Board `json:"board"`
}

type NewBoard struct {
	Rows []string `json:"rows"`
}
