// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type GamesConnection struct {
	Edges    []*Game   `json:"edges"`
	PageInfo *PageInfo `json:"pageInfo"`
}

type GamesEdge struct {
	Cursor string `json:"cursor"`
	Node   *Game  `json:"node"`
}

type PageInfo struct {
	StartCursor string `json:"startCursor"`
	EndCursor   string `json:"endCursor"`
	HasNextPage *bool  `json:"hasNextPage"`
}
